/*
 * DO NOT EDIT THIS FILE.
 *
 * File:   main_helpers.h
 * Author: marwan
 *
 */

#ifndef MAIN_HELPERS_H
#define MAIN_HELPERS_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * pyramid_input:  Takes a starting position as input from the user.
 *
 * Parameters:
 *      board[] - An array of 15 integers.
 *                The array will contain the board upon completion.
 */

int get_choice(const char *prompt);

#include<stdbool.h>
#ifdef __cplusplus
}
#endif

#endif /* PYRAMID_HELPERS_H */
